from collections.abc import Sequence


class Context:
    def __init__(self) -> None: ...

    def add_proto(self, filename: str, content: str) -> None: ...

    def to_json(self, message_type: str, data: bytes, *, include_defaults: bool = False, pretty: bool = False, proto_field_names: bool = False, enums_as_ints: bool = False, unquote_int64: bool = False) -> str: ...

    def from_json(self, message_type: str, json: str) -> bytes: ...

    def message_type_from_index(self, filename: str, message_index: Sequence[int]) -> str: ...
