name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Build SDist
      run: uv build --sdist

    - uses: actions/upload-artifact@v7
      with:
        name: sdist
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-13
          - os: macos-latest
          - os: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - uses: pypa/cibuildwheel@v3.4.1
      env:
        CIBW_BUILD: "cp312-*"
        CIBW_ARCHS_MACOS: auto
        CIBW_BUILD_FRONTEND: "build[uv]"

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheels-${{ matrix.os }}
        path: wheelhouse/*.whl


  publish:
    name: Publish to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    environment: pypi
    permissions:
      id-token: write

    steps:
    - uses: astral-sh/setup-uv@v7

    - uses: actions/download-artifact@v8
      with:
        path: dist
        merge-multiple: true

    - name: Publish to PyPI
      run: uv publish dist/*
